//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMachineACafeService.DataLayer.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class userchoices
    {
        public string NumBadge { get; set; }
        public string TypeBoisson { get; set; }
        public Nullable<int> QuantiteSucre { get; set; }
        public Nullable<int> UtiliserSonMug { get; set; }
        public Nullable<System.DateTime> LastSelectionDate { get; set; }
    }
}
