USE [master]
GO

/****** Object:  Database [MachineAcafe]    Script Date: 18/04/2018 12:33:14 ******/
CREATE DATABASE [MachineAcafe] ON  PRIMARY 
( NAME = N'MachineAcafe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\MachineAcafe.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MachineAcafe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\MachineAcafe_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MachineAcafe] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MachineAcafe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MachineAcafe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MachineAcafe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MachineAcafe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MachineAcafe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MachineAcafe] SET ARITHABORT OFF 
GO

ALTER DATABASE [MachineAcafe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MachineAcafe] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MachineAcafe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MachineAcafe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MachineAcafe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MachineAcafe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MachineAcafe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MachineAcafe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MachineAcafe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MachineAcafe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MachineAcafe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MachineAcafe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MachineAcafe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MachineAcafe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MachineAcafe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MachineAcafe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MachineAcafe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MachineAcafe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MachineAcafe] SET RECOVERY FULL 
GO

ALTER DATABASE [MachineAcafe] SET  MULTI_USER 
GO

ALTER DATABASE [MachineAcafe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MachineAcafe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MachineAcafe] SET  READ_WRITE 
GO